import 'dart:convert';
import 'dart:io';

const localeCodes = [
  'en',
  'es',
  'pt_BR',
  'de',
  'fr',
  'ar',
  'tr',
  'ja',
  'id',
  'ru',
  'it',
  'ko',
  'pl',
  'nl',
  'hi',
  'vi',
  'uk',
  'th',
  'zh_Hans',
  'zh_Hant',
  'fa',
  'ur',
  'fil',
  'ms',
  'ro',
  'cs',
  'sv',
  'da',
  'nb',
  'el',
];

/// Compile the reviewed JSON catalogs into synchronous, typed Dart constants.
/// Run from the app root. Incomplete catalogs never replace the generated file.
/// --check additionally verifies that the committed output is current.
void main(List<String> args) {
  final check = args.contains('--check');
  final source = readCatalog('source');
  final catalogs = <String, Map<String, String>>{};
  var incomplete = false;
  for (final code in localeCodes) {
    final catalog = readCatalog(code);
    for (final entry in catalog.entries) {
      if (!source.containsKey(entry.key)) {
        throw FormatException('$code: unknown key ${entry.key}');
      }
      if (entry.value.trim().isEmpty) {
        throw FormatException('$code: empty translation for ${entry.key}');
      }
      if (entry.value.contains('\uFFFD')) {
        throw FormatException('$code: invalid Unicode for ${entry.key}');
      }
      if (placeholders(entry.value) != placeholders(source[entry.key]!)) {
        throw FormatException('$code: placeholders differ for ${entry.key}');
      }
    }
    final missing = source.keys
        .where((key) => !catalog.containsKey(key))
        .length;
    if (missing > 0) {
      incomplete = true;
      stderr.writeln('$code: $missing missing translations');
    }
    catalogs[code] = catalog;
  }
  if (incomplete) {
    exitCode = 1;
    return;
  }
  final output = StringBuffer(
    '// Generated by tool/l10n/generate_catalogs.dart. Do not edit.\n\n',
  );
  output.writeln('const sourceCatalog = <String, String>${dartMap(source)};');
  output.writeln(
    '\nconst translationCatalogs = <String, Map<String, String>>{',
  );
  for (final entry in catalogs.entries) {
    output.writeln('  ${quote(entry.key)}: ${dartMap(entry.value)},');
  }
  output.writeln('};');
  final file = File('lib/l10n/generated_catalogs.dart');
  if (check) {
    if (!file.existsSync() || file.readAsStringSync() != output.toString()) {
      stderr.writeln('Generated catalogs are out of date. Run the generator.');
      exitCode = 1;
    }
  } else {
    file.writeAsStringSync(output.toString());
  }
}

Map<String, String> readCatalog(String name) {
  final decoded = jsonDecode(
    File('lib/l10n/catalogs/$name.json').readAsStringSync(),
  );
  if (decoded is! Map<String, dynamic> ||
      decoded.values.any((value) => value is! String)) {
    throw FormatException('$name must be a JSON object of string translations');
  }
  return decoded.cast<String, String>();
}

String placeholders(String value) {
  final tokens = RegExp(
    r'\{[A-Za-z_][A-Za-z0-9_]*\}',
  ).allMatches(value).map((m) => m.group(0)!).toList()..sort();
  return tokens.join('|');
}

String quote(String value) => jsonEncode(value).replaceAll(r'$', r'\$');
String dartMap(Map<String, String> entries) {
  final keys = entries.keys.toList()..sort();
  return '{\n${keys.map((key) => '    ${quote(key)}: ${quote(entries[key]!)},').join('\n')}\n  }';
}
